//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServiceClient.JobProcessorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobEnvelopeStatus", Namespace="http://schemas.datacontract.org/2004/07/SolidFrameworkService")]
    [System.SerializableAttribute()]
    public partial class JobEnvelopeStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.JobStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.JobStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Services.Plumbing")]
    public enum JobStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Started = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimedOut = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadData = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTables = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoImages = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTagged = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPdfA = 2048,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimedOutFailure = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFailure = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadDataFailure = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalErrorFailure = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTablesFailure = 260,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoImagesFailure = 516,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTaggedFailure = 1028,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPdfAFailure = 2052,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToWordJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToWordJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DetectTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.WordDocumentType DocTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.HeaderAndFooterMode HeadersAndFootersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ImageAnchoringMode ImageAnchorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ReconstructionMode ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.TextRecovery TextRecoveryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DetectTables {
            get {
                return this.DetectTablesField;
            }
            set {
                if ((this.DetectTablesField.Equals(value) != true)) {
                    this.DetectTablesField = value;
                    this.RaisePropertyChanged("DetectTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.WordDocumentType DocType {
            get {
                return this.DocTypeField;
            }
            set {
                if ((this.DocTypeField.Equals(value) != true)) {
                    this.DocTypeField = value;
                    this.RaisePropertyChanged("DocType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.HeaderAndFooterMode HeadersAndFooters {
            get {
                return this.HeadersAndFootersField;
            }
            set {
                if ((this.HeadersAndFootersField.Equals(value) != true)) {
                    this.HeadersAndFootersField = value;
                    this.RaisePropertyChanged("HeadersAndFooters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ImageAnchoringMode ImageAnchor {
            get {
                return this.ImageAnchorField;
            }
            set {
                if ((this.ImageAnchorField.Equals(value) != true)) {
                    this.ImageAnchorField = value;
                    this.RaisePropertyChanged("ImageAnchor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ReconstructionMode Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.TextRecovery TextRecovery {
            get {
                return this.TextRecoveryField;
            }
            set {
                if ((this.TextRecoveryField.Equals(value) != true)) {
                    this.TextRecoveryField = value;
                    this.RaisePropertyChanged("TextRecovery");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordDocumentType", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum WordDocumentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WordML = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rtf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Txt = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doc = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocX = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderAndFooterMode", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum HeaderAndFooterMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ignore = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageAnchoringMode", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum ImageAnchoringMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Automatic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paragraph = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Page = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoveImages = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReconstructionMode", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum ReconstructionMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Flowing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exact = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Continuous = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlainText = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoColumns = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextRecovery", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum TextRecovery : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Automatic = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Always = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Never = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToExcelJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToExcelJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutoDetectSeparatorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CombineTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.DecimalSeparator DecimalSeperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NonTableContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.TextRecovery TextRecoveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ThousandsSeparator ThousandsSeperatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoDetectSeparators {
            get {
                return this.AutoDetectSeparatorsField;
            }
            set {
                if ((this.AutoDetectSeparatorsField.Equals(value) != true)) {
                    this.AutoDetectSeparatorsField = value;
                    this.RaisePropertyChanged("AutoDetectSeparators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CombineTables {
            get {
                return this.CombineTablesField;
            }
            set {
                if ((this.CombineTablesField.Equals(value) != true)) {
                    this.CombineTablesField = value;
                    this.RaisePropertyChanged("CombineTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.DecimalSeparator DecimalSeperator {
            get {
                return this.DecimalSeperatorField;
            }
            set {
                if ((this.DecimalSeperatorField.Equals(value) != true)) {
                    this.DecimalSeperatorField = value;
                    this.RaisePropertyChanged("DecimalSeperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NonTableContent {
            get {
                return this.NonTableContentField;
            }
            set {
                if ((this.NonTableContentField.Equals(value) != true)) {
                    this.NonTableContentField = value;
                    this.RaisePropertyChanged("NonTableContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.TextRecovery TextRecovery {
            get {
                return this.TextRecoveryField;
            }
            set {
                if ((this.TextRecoveryField.Equals(value) != true)) {
                    this.TextRecoveryField = value;
                    this.RaisePropertyChanged("TextRecovery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ThousandsSeparator ThousandsSeperator {
            get {
                return this.ThousandsSeperatorField;
            }
            set {
                if ((this.ThousandsSeperatorField.Equals(value) != true)) {
                    this.ThousandsSeperatorField = value;
                    this.RaisePropertyChanged("ThousandsSeperator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecimalSeparator", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum DecimalSeparator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Period = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comma = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThousandsSeparator", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum ThousandsSeparator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comma = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Period = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Space = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToPowerPointJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToPowerPointJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DetectListsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.TextRecovery TextRecoveryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DetectLists {
            get {
                return this.DetectListsField;
            }
            set {
                if ((this.DetectListsField.Equals(value) != true)) {
                    this.DetectListsField = value;
                    this.RaisePropertyChanged("DetectLists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.TextRecovery TextRecovery {
            get {
                return this.TextRecoveryField;
            }
            set {
                if ((this.TextRecoveryField.Equals(value) != true)) {
                    this.TextRecoveryField = value;
                    this.RaisePropertyChanged("TextRecovery");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToPdfAJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToPdfAJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ValidationMode ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ValidationMode Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Searchable {
            get {
                return this.SearchableField;
            }
            set {
                if ((this.SearchableField.Equals(value) != true)) {
                    this.SearchableField = value;
                    this.RaisePropertyChanged("Searchable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationMode", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Plumbing")]
    public enum ValidationMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA1B = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA1A = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA2B = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA2A = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA2U = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA3B = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA3A = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfA3U = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToTextJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToTextJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CharacterEncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.LineTerminator TerminatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CharacterEncoding {
            get {
                return this.CharacterEncodingField;
            }
            set {
                if ((this.CharacterEncodingField.Equals(value) != true)) {
                    this.CharacterEncodingField = value;
                    this.RaisePropertyChanged("CharacterEncoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineLength {
            get {
                return this.LineLengthField;
            }
            set {
                if ((this.LineLengthField.Equals(value) != true)) {
                    this.LineLengthField = value;
                    this.RaisePropertyChanged("LineLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.LineTerminator Terminator {
            get {
                return this.TerminatorField;
            }
            set {
                if ((this.TerminatorField.Equals(value) != true)) {
                    this.TerminatorField = value;
                    this.RaisePropertyChanged("Terminator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineTerminator", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum LineTerminator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Platform = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windows = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OSX = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToDataJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToDataJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CharacterEncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.DelimiterOptions DelimiterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.LineTerminator TerminatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CharacterEncoding {
            get {
                return this.CharacterEncodingField;
            }
            set {
                if ((this.CharacterEncodingField.Equals(value) != true)) {
                    this.CharacterEncodingField = value;
                    this.RaisePropertyChanged("CharacterEncoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.DelimiterOptions Delimiter {
            get {
                return this.DelimiterField;
            }
            set {
                if ((this.DelimiterField.Equals(value) != true)) {
                    this.DelimiterField = value;
                    this.RaisePropertyChanged("Delimiter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.LineTerminator Terminator {
            get {
                return this.TerminatorField;
            }
            set {
                if ((this.TerminatorField.Equals(value) != true)) {
                    this.TerminatorField = value;
                    this.RaisePropertyChanged("Terminator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelimiterOptions", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum DelimiterOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comma = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Semicolon = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tab = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToHtmlJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToHtmlJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ImageDocumentType ImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.HtmlImages ImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.HtmlNavigation NavigationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.HtmlSplittingUsing SplitUsingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ImageDocumentType ImageType {
            get {
                return this.ImageTypeField;
            }
            set {
                if ((this.ImageTypeField.Equals(value) != true)) {
                    this.ImageTypeField = value;
                    this.RaisePropertyChanged("ImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.HtmlImages Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((this.ImagesField.Equals(value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.HtmlNavigation Navigation {
            get {
                return this.NavigationField;
            }
            set {
                if ((this.NavigationField.Equals(value) != true)) {
                    this.NavigationField = value;
                    this.RaisePropertyChanged("Navigation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.HtmlSplittingUsing SplitUsing {
            get {
                return this.SplitUsingField;
            }
            set {
                if ((this.SplitUsingField.Equals(value) != true)) {
                    this.SplitUsingField = value;
                    this.RaisePropertyChanged("SplitUsing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WidthLimit {
            get {
                return this.WidthLimitField;
            }
            set {
                if ((this.WidthLimitField.Equals(value) != true)) {
                    this.WidthLimitField = value;
                    this.RaisePropertyChanged("WidthLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageDocumentType", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum ImageDocumentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bmp = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jpeg = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Png = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tiff = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gif = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlImages", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum HtmlImages : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Link = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ignore = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Embed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlNavigation", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters")]
    public enum HtmlNavigation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleWithoutNavigation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleWithEmbeddedNavigation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SplitIntoMultipleFiles = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlSplittingUsing", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters")]
    public enum HtmlSplittingUsing : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pages = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bookmarks = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Headings = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfToImagesJobEnvelope", Namespace="http://schemas.datacontract.org/2004/07/JobProcessorService.JobEnvelopes")]
    [System.SerializableAttribute()]
    public partial class PdfToImagesJobEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ImageConversionType ConversionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestServiceClient.JobProcessorServiceReference.ImageDocumentType ImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageDPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ImageConversionType ConversionType {
            get {
                return this.ConversionTypeField;
            }
            set {
                if ((this.ConversionTypeField.Equals(value) != true)) {
                    this.ConversionTypeField = value;
                    this.RaisePropertyChanged("ConversionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestServiceClient.JobProcessorServiceReference.ImageDocumentType ImageType {
            get {
                return this.ImageTypeField;
            }
            set {
                if ((this.ImageTypeField.Equals(value) != true)) {
                    this.ImageTypeField = value;
                    this.RaisePropertyChanged("ImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageDPI {
            get {
                return this.PageDPIField;
            }
            set {
                if ((this.PageDPIField.Equals(value) != true)) {
                    this.PageDPIField = value;
                    this.RaisePropertyChanged("PageDPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageConversionType", Namespace="http://schemas.datacontract.org/2004/07/SolidFramework.Converters.Plumbing")]
    public enum ImageConversionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExtractImages = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExtractPages = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobProcessorServiceReference.IjobProcessorService")]
    public interface IjobProcessorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/GetJobStatus", ReplyAction="http://tempuri.org/IjobProcessorService/GetJobStatusResponse")]
        TestServiceClient.JobProcessorServiceReference.JobEnvelopeStatus GetJobStatus(int jobid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/GetJobStatus", ReplyAction="http://tempuri.org/IjobProcessorService/GetJobStatusResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobEnvelopeStatus> GetJobStatusAsync(int jobid);
        
        // CODEGEN: 消息 DownloadRequest 的包装名称(DownloadRequest)以后生成的消息协定与默认值(DownloadFile)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/DownloadFile", ReplyAction="http://tempuri.org/IjobProcessorService/DownloadFileResponse")]
        TestServiceClient.JobProcessorServiceReference.RemoteFileInfo DownloadFile(TestServiceClient.JobProcessorServiceReference.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/DownloadFile", ReplyAction="http://tempuri.org/IjobProcessorService/DownloadFileResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.RemoteFileInfo> DownloadFileAsync(TestServiceClient.JobProcessorServiceReference.DownloadRequest request);
        
        // CODEGEN: 消息 RemoteWordJob 的包装名称(RemoteWordJob)以后生成的消息协定与默认值(UploadWordJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadWordJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadWordJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadWordJob(TestServiceClient.JobProcessorServiceReference.RemoteWordJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadWordJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadWordJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadWordJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteWordJob request);
        
        // CODEGEN: 消息 RemoteExcelJob 的包装名称(RemoteExcelJob)以后生成的消息协定与默认值(UploadExcelJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadExcelJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadExcelJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadExcelJob(TestServiceClient.JobProcessorServiceReference.RemoteExcelJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadExcelJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadExcelJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadExcelJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteExcelJob request);
        
        // CODEGEN: 消息 RemotePowerPointJob 的包装名称(RemotePowerPointJob)以后生成的消息协定与默认值(UploadPowerPointJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadPowerPointJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadPowerPointJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadPowerPointJob(TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadPowerPointJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadPowerPointJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadPowerPointJobAsync(TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob request);
        
        // CODEGEN: 消息 RemotePdfAJob 的包装名称(RemotePdfAJob)以后生成的消息协定与默认值(UploadPdfAJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadPdfAJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadPdfAJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadPdfAJob(TestServiceClient.JobProcessorServiceReference.RemotePdfAJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadPdfAJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadPdfAJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadPdfAJobAsync(TestServiceClient.JobProcessorServiceReference.RemotePdfAJob request);
        
        // CODEGEN: 消息 RemoteTextJob 的包装名称(RemoteTextJob)以后生成的消息协定与默认值(UploadTextJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadTextJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadTextJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadTextJob(TestServiceClient.JobProcessorServiceReference.RemoteTextJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadTextJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadTextJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadTextJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteTextJob request);
        
        // CODEGEN: 消息 RemoteDataJob 的包装名称(RemoteDataJob)以后生成的消息协定与默认值(UploadDataJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadDataJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadDataJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadDataJob(TestServiceClient.JobProcessorServiceReference.RemoteDataJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadDataJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadDataJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadDataJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteDataJob request);
        
        // CODEGEN: 消息 RemoteHtmlJob 的包装名称(RemoteHtmlJob)以后生成的消息协定与默认值(UploadHtmlJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadHtmlJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadHtmlJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadHtmlJob(TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadHtmlJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadHtmlJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadHtmlJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob request);
        
        // CODEGEN: 消息 RemoteImageJob 的包装名称(RemoteImageJob)以后生成的消息协定与默认值(UploadImageJob)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadImageJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadImageJobResponse")]
        TestServiceClient.JobProcessorServiceReference.JobId UploadImageJob(TestServiceClient.JobProcessorServiceReference.RemoteImageJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IjobProcessorService/UploadImageJob", ReplyAction="http://tempuri.org/IjobProcessorService/UploadImageJobResponse")]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadImageJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteImageJob request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int JobId;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(int JobId) {
            this.JobId = JobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string FileName, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteWordJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteWordJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToWordJobEnvelope WordEnvelope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteWordJob() {
        }
        
        public RemoteWordJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToWordJobEnvelope WordEnvelope, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.WordEnvelope = WordEnvelope;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JobId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JobId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        public JobId() {
        }
        
        public JobId(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteExcelJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteExcelJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToExcelJobEnvelope ExcelEnvelope;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteExcelJob() {
        }
        
        public RemoteExcelJob(TestServiceClient.JobProcessorServiceReference.PdfToExcelJobEnvelope ExcelEnvelope, string FileName, long Length, System.IO.Stream FileByteStream) {
            this.ExcelEnvelope = ExcelEnvelope;
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemotePowerPointJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemotePowerPointJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToPowerPointJobEnvelope PowerPointEnvelope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemotePowerPointJob() {
        }
        
        public RemotePowerPointJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToPowerPointJobEnvelope PowerPointEnvelope, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.PowerPointEnvelope = PowerPointEnvelope;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemotePdfAJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemotePdfAJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToPdfAJobEnvelope PdfAEnvelope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemotePdfAJob() {
        }
        
        public RemotePdfAJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToPdfAJobEnvelope PdfAEnvelope, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.PdfAEnvelope = PdfAEnvelope;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteTextJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteTextJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToTextJobEnvelope TextEnvelope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteTextJob() {
        }
        
        public RemoteTextJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToTextJobEnvelope TextEnvelope, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.TextEnvelope = TextEnvelope;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteDataJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteDataJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToDataJobEnvelope DataEnvelope;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteDataJob() {
        }
        
        public RemoteDataJob(TestServiceClient.JobProcessorServiceReference.PdfToDataJobEnvelope DataEnvelope, string FileName, long Length, System.IO.Stream FileByteStream) {
            this.DataEnvelope = DataEnvelope;
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteHtmlJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteHtmlJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToHtmlJobEnvelope HtmlEnvelope;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteHtmlJob() {
        }
        
        public RemoteHtmlJob(string FileName, TestServiceClient.JobProcessorServiceReference.PdfToHtmlJobEnvelope HtmlEnvelope, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.HtmlEnvelope = HtmlEnvelope;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteImageJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteImageJob {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServiceClient.JobProcessorServiceReference.PdfToImagesJobEnvelope ImageEnvelope;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteImageJob() {
        }
        
        public RemoteImageJob(string FileName, TestServiceClient.JobProcessorServiceReference.PdfToImagesJobEnvelope ImageEnvelope, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.ImageEnvelope = ImageEnvelope;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IjobProcessorServiceChannel : TestServiceClient.JobProcessorServiceReference.IjobProcessorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IjobProcessorServiceClient : System.ServiceModel.ClientBase<TestServiceClient.JobProcessorServiceReference.IjobProcessorService>, TestServiceClient.JobProcessorServiceReference.IjobProcessorService {
        
        public IjobProcessorServiceClient() {
        }
        
        public IjobProcessorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IjobProcessorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IjobProcessorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IjobProcessorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestServiceClient.JobProcessorServiceReference.JobEnvelopeStatus GetJobStatus(int jobid) {
            return base.Channel.GetJobStatus(jobid);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobEnvelopeStatus> GetJobStatusAsync(int jobid) {
            return base.Channel.GetJobStatusAsync(jobid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.RemoteFileInfo TestServiceClient.JobProcessorServiceReference.IjobProcessorService.DownloadFile(TestServiceClient.JobProcessorServiceReference.DownloadRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public string DownloadFile(int JobId, out long Length, out System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.DownloadRequest inValue = new TestServiceClient.JobProcessorServiceReference.DownloadRequest();
            inValue.JobId = JobId;
            TestServiceClient.JobProcessorServiceReference.RemoteFileInfo retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).DownloadFile(inValue);
            Length = retVal.Length;
            FileByteStream = retVal.FileByteStream;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.RemoteFileInfo> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.DownloadFileAsync(TestServiceClient.JobProcessorServiceReference.DownloadRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.RemoteFileInfo> DownloadFileAsync(int JobId) {
            TestServiceClient.JobProcessorServiceReference.DownloadRequest inValue = new TestServiceClient.JobProcessorServiceReference.DownloadRequest();
            inValue.JobId = JobId;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).DownloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadWordJob(TestServiceClient.JobProcessorServiceReference.RemoteWordJob request) {
            return base.Channel.UploadWordJob(request);
        }
        
        public int UploadWordJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToWordJobEnvelope WordEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteWordJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteWordJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.WordEnvelope = WordEnvelope;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadWordJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadWordJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteWordJob request) {
            return base.Channel.UploadWordJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadWordJobAsync(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToWordJobEnvelope WordEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteWordJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteWordJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.WordEnvelope = WordEnvelope;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadWordJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadExcelJob(TestServiceClient.JobProcessorServiceReference.RemoteExcelJob request) {
            return base.Channel.UploadExcelJob(request);
        }
        
        public int UploadExcelJob(TestServiceClient.JobProcessorServiceReference.PdfToExcelJobEnvelope ExcelEnvelope, string FileName, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteExcelJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteExcelJob();
            inValue.ExcelEnvelope = ExcelEnvelope;
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadExcelJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadExcelJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteExcelJob request) {
            return base.Channel.UploadExcelJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadExcelJobAsync(TestServiceClient.JobProcessorServiceReference.PdfToExcelJobEnvelope ExcelEnvelope, string FileName, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteExcelJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteExcelJob();
            inValue.ExcelEnvelope = ExcelEnvelope;
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadExcelJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadPowerPointJob(TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob request) {
            return base.Channel.UploadPowerPointJob(request);
        }
        
        public int UploadPowerPointJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToPowerPointJobEnvelope PowerPointEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob inValue = new TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.PowerPointEnvelope = PowerPointEnvelope;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadPowerPointJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadPowerPointJobAsync(TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob request) {
            return base.Channel.UploadPowerPointJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadPowerPointJobAsync(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToPowerPointJobEnvelope PowerPointEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob inValue = new TestServiceClient.JobProcessorServiceReference.RemotePowerPointJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.PowerPointEnvelope = PowerPointEnvelope;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadPowerPointJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadPdfAJob(TestServiceClient.JobProcessorServiceReference.RemotePdfAJob request) {
            return base.Channel.UploadPdfAJob(request);
        }
        
        public int UploadPdfAJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToPdfAJobEnvelope PdfAEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemotePdfAJob inValue = new TestServiceClient.JobProcessorServiceReference.RemotePdfAJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.PdfAEnvelope = PdfAEnvelope;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadPdfAJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadPdfAJobAsync(TestServiceClient.JobProcessorServiceReference.RemotePdfAJob request) {
            return base.Channel.UploadPdfAJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadPdfAJobAsync(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToPdfAJobEnvelope PdfAEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemotePdfAJob inValue = new TestServiceClient.JobProcessorServiceReference.RemotePdfAJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.PdfAEnvelope = PdfAEnvelope;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadPdfAJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadTextJob(TestServiceClient.JobProcessorServiceReference.RemoteTextJob request) {
            return base.Channel.UploadTextJob(request);
        }
        
        public int UploadTextJob(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToTextJobEnvelope TextEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteTextJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteTextJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.TextEnvelope = TextEnvelope;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadTextJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadTextJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteTextJob request) {
            return base.Channel.UploadTextJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadTextJobAsync(string FileName, long Length, TestServiceClient.JobProcessorServiceReference.PdfToTextJobEnvelope TextEnvelope, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteTextJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteTextJob();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.TextEnvelope = TextEnvelope;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadTextJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadDataJob(TestServiceClient.JobProcessorServiceReference.RemoteDataJob request) {
            return base.Channel.UploadDataJob(request);
        }
        
        public int UploadDataJob(TestServiceClient.JobProcessorServiceReference.PdfToDataJobEnvelope DataEnvelope, string FileName, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteDataJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteDataJob();
            inValue.DataEnvelope = DataEnvelope;
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadDataJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadDataJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteDataJob request) {
            return base.Channel.UploadDataJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadDataJobAsync(TestServiceClient.JobProcessorServiceReference.PdfToDataJobEnvelope DataEnvelope, string FileName, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteDataJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteDataJob();
            inValue.DataEnvelope = DataEnvelope;
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadDataJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadHtmlJob(TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob request) {
            return base.Channel.UploadHtmlJob(request);
        }
        
        public int UploadHtmlJob(string FileName, TestServiceClient.JobProcessorServiceReference.PdfToHtmlJobEnvelope HtmlEnvelope, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob();
            inValue.FileName = FileName;
            inValue.HtmlEnvelope = HtmlEnvelope;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadHtmlJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadHtmlJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob request) {
            return base.Channel.UploadHtmlJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadHtmlJobAsync(string FileName, TestServiceClient.JobProcessorServiceReference.PdfToHtmlJobEnvelope HtmlEnvelope, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteHtmlJob();
            inValue.FileName = FileName;
            inValue.HtmlEnvelope = HtmlEnvelope;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadHtmlJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServiceClient.JobProcessorServiceReference.JobId TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadImageJob(TestServiceClient.JobProcessorServiceReference.RemoteImageJob request) {
            return base.Channel.UploadImageJob(request);
        }
        
        public int UploadImageJob(string FileName, TestServiceClient.JobProcessorServiceReference.PdfToImagesJobEnvelope ImageEnvelope, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteImageJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteImageJob();
            inValue.FileName = FileName;
            inValue.ImageEnvelope = ImageEnvelope;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            TestServiceClient.JobProcessorServiceReference.JobId retVal = ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadImageJob(inValue);
            return retVal.ID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> TestServiceClient.JobProcessorServiceReference.IjobProcessorService.UploadImageJobAsync(TestServiceClient.JobProcessorServiceReference.RemoteImageJob request) {
            return base.Channel.UploadImageJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServiceClient.JobProcessorServiceReference.JobId> UploadImageJobAsync(string FileName, TestServiceClient.JobProcessorServiceReference.PdfToImagesJobEnvelope ImageEnvelope, long Length, System.IO.Stream FileByteStream) {
            TestServiceClient.JobProcessorServiceReference.RemoteImageJob inValue = new TestServiceClient.JobProcessorServiceReference.RemoteImageJob();
            inValue.FileName = FileName;
            inValue.ImageEnvelope = ImageEnvelope;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((TestServiceClient.JobProcessorServiceReference.IjobProcessorService)(this)).UploadImageJobAsync(inValue);
        }
    }
}
